[package]
name = "nanocodex-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
nanocodex-memory.workspace = true
axum.workspace = true
chrono.workspace = true
eyre.workspace = true
futures-util.workspace = true
nanocodex.workspace = true
nanocodex-subagents.workspace = true
jsonschema.workspace = true
reqwest = { workspace = true, features = ["stream"] }
url.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util.workspace = true
uuid.workspace = true

[lints]
workspace = true
